### ISSUE TITLE
should we give this incubation more time?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/element-capture#1]
Not seeing any activity since the repo was created a few months ago. 

Is there still interest in pursuing this?

**Comment by yoavweiss** [comment]
^^ @eladalon1983

**Comment by eladalon1983** [comment]
I have presented this at the first Screen Capture Community Group last week ([slides](https://docs.google.com/presentation/d/12rkZiPoOSz8jRsVpT2O5JKPowcByo1O5dL4sJQjYgKQ/edit#slide=id.g20e417a735b_0_3650), [minutes](https://github.com/screen-share/meetings/blob/main/minutes/2023-02-16.md)), and we decided to incubate this [here](https://github.com/screen-share/element-capture). I'll soon produce the first spec draft.

For interested Googlers, the design doc is coming along [here](https://docs.google.com/document/d/1aYtTzDyNaifwqm-d_cKlLUuMpITx17HWEEV1lcPuS-4/edit?usp=sharing).

So I guess the TL;DR is that we can eliminate this repo. Do you concur, @yoavweiss?

**Comment by yoavweiss** [comment]
s/eliminate/archive/ but otherwise sure

**Comment by eladalon1983** [comment]
Cool. Please let me know if any further action is required on my part.

**Comment by marcoscaceres** [comment]
Ok, cool. @yoavweiss, do you want to do the archiving honors?

**Comment by yoavweiss** [comment]
sure! :)
